name: GitHub Actions - Configuração de variavel de repositorio
run-name: Running - Var Repo Config
on: [push, workflow_dispatch]
jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:
            -   name: Comentário
                run: |
                    echo "${{secrets.test_secret}}"