name: GitHub Actions - Matrix Strategy Template
run-name: Running - Matrix
on: [push, workflow_dispatch]


jobs:
      matrix_job:
          runs-on: ubuntu-latest
          strategy:
              matrix:
                  navegador: [chrome, firefox, edge]
                  tag: [tag1, tag2, tag3]
              fail-fast: false
          steps:
              -   name: Comentário
                  run: |
                      echo "Testando ${{ matrix.navegador }}"
                      echo "Tag: ${{ matrix.tag }}"