name: GitHub Actions - Workflow Run Template
run-name: Running - Workflow run Basic Template
on:
  workflow_run:
    workflows: ["GitHub Actions - Trigger 1"]
jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:
            - name: Comentário
              run: echo "Workflow que foi trigado"