name: GitHub Actions - Workflow run types
run-name: Running - Workflow run types
on:
    workflow_run:
        workflows: [GitHub Actions - Trigger 1]
        types: [completed]
jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:
            -   name: Comentário
                run: |
                    echo "Workflow que foi trigado"