name: GitHub Actions Workflow Dispatch Example - String
run-name: Running - ${{github.event_name}}
on: 
    workflow_dispatch:
        inputs:
            browser:
                description: Selecione o Browser
                type: string
jobs:
    on-workflow-dispatch:
        runs-on: ubuntu-latest
        steps:
        -   name: Comentário
            run: |
                echo "Comentário Workflow Dispatch - Browser: ${{inputs.browser}}"