name: GitHub Actions - Workflow Dispatch - Boolean Input
run-name: Running ${{github.event_name}}
on:
  workflow_dispatch:
    inputs:
      severidade:
        description: funcionalidade critica?
        type: boolean
jobs:
    on-workflow-dispatch:
        runs-on: ubuntu-latest
        steps:
            - name: Check the value of the input
              run: |
                echo "Comentário Workflow Dispatch - Boolean Input: ${{inputs.severidade}}"