name: GitHub Actions - Workflow Run time multi-workflow
run-name: Running - Workflow Run muiltiple-workflow
on:
  workflow_run:
    workflows: [GitHub Actions - Trigger 1, GitHub Actions - Trigger 2]
    types: [completed]
    branches: [main]
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: echo "Workflow que foi trigado"