name: GitHub Actions - Push - General
run-name: Running ${{github.event_name}}
on: 
    push:
        branches:
            - master
            - main
            - develop
            # branches-ignore:
            # - 'release/**'
        paths:
            - '**.txt'
jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:
            -   name: Comentário
                run: |
                    echo "Comentário PUSH WORKFLOW"
                    echo "Branch: ${{github.ref}}"
                    echo "Evento: ${{github.event_name}}"